# booking-service — DEV profil
spring.datasource.url=jdbc:postgresql://localhost:5432/brico_bookings
spring.datasource.username=brico
spring.datasource.password=brico123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.ba.unsa.etf.nwt=DEBUG
